### ISSUE TITLE
New API Source: USA

### ISSUE THREAD

**Issue by aanunez** [tertek/redcap-address-auto-complete#10]
The US Census Bureau exposes a public [geocoder service ](https://geocoding.geo.census.gov/geocoder/) for address lookup that I think will be sufficient to enhance this EM. I plan to investigate if the API is sufficient and do dev for this enhancement myself, but I wanted to let the maintainer know and anyone else who might consider also doing dev for this. The API is free to use, seemingly without any restrictions. I don't currently have a timeline for this.

**Comment by tertek** [comment]
Hi @aanunez 
it would be nice to extend the API sources to also support US addresses.
I had a quick look into API and it seems as if it is not designed to support search for plain strings as query, also see the [Geocoding Definition](https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.html): "The current Geocoding Services engine requires a structure address be provided." 

This means that it would not work with this module, since it also has to support queries where parts of an address without format (plain string input) return valid address suggestions.

Please let me know if you need further information about the interface given by this module.
